### ISSUE TITLE
pip install from git doesn't register module correctly

### ISSUE THREAD

**Issue by rhoadesScholar** [funkelab/funlib.persistence#1]
![image](https://github.com/funkelab/funlib.persistence/assets/37990507/f551ba90-c03b-4e69-b388-e153c4c32c7f)

**Comment by msayr** [comment]
I'm experiencing this as well.

**Comment by msayr** [comment]
@rhoadesScholar do you have a workaround for this?

**Comment by pattonw** [comment]
very strange. Not sure what the UNKNOWN is about. Will look into it

**Comment by rhoadesScholar** [comment]
> @rhoadesScholar do you have a workaround for this?

Sort of, but it's pretty dirty: 
I downloaded the only file I needed from the package directly into the project I'm working on that requires it.

My project is just some quick and dirty analysis code - nothing production-grade. So this hack works for me, but I would not recommend this approach for anything needing a longterm solution.

**Comment by pattonw** [comment]
is this still an issue? I can't recreate it

**Comment by rhoadesScholar** [comment]
I haven't had this issue for some time. Closing it.
