### ISSUE TITLE
Support hdf5 in datasets

### ISSUE THREAD

**Issue by Mohinta2892** [funkelab/funlib.persistence#8]
Hello!

Can file type `hdf5` please be added to `datasets.py`?

Currently it supports `h5` and `hdf` (please see below), but is unable to read files with ext `.hdf5`.

Line 440 of `datasets.py`:
` elif filename.endswith(".h5") or filename.endswith(".hdf")`

Best,
Samia

**Comment by pattonw** [comment]
Done!
